version: "3.9"

# application stack
#  - Each server when running will create a separate container
services:

  identity: # This container used for initializing Identity Provider - Keycloak
    image: quay.io/keycloak/keycloak:26.0.2
    container_name: "identity"
    command:
      - start-dev
      - --import-realm
      - --spi-theme-cache-themes=false
      - --spi-theme-cache-templates=false
    environment:
      - KC_DB=${MSSQL_HOSTNAME}
      - KC_DB_URL=${MSSQL_DATASOURCE_URL};databaseName=identity_db;encrypt=false
      - KC_DB_USERNAME=${MSSQL_SA_USERNAME}
      - KC_DB_PASSWORD=${MSSQL_SA_PASSWORD}
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_BOOTSTRAP_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_BOOTSTRAP_ADMIN_PASSWORD}
    volumes:
      - ./identity/drivers:/opt/keycloak/providers
      - ./identity/themes/storefront-theme:/opt/keycloak/themes/storefront-theme
      - ./identity/themes/backoffice-theme:/opt/keycloak/themes/backoffice-theme
      - ./identity/realms/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    networks:
      - course-network

  mssql:  # This container used for initializing SQL Server
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: "mssql"
    hostname: "mssql"
    ports:
      - "14330:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./mssql/data/mssql/backups:/var/opt/mssql/backups # SQL scripts, backups
      - ./mssql/data/mssql/data:/var/opt/mssql/data       # Database files (.mdf, .ldf)
      - ./mssql/data/mssql/log:/var/opt/mssql/log         # Log files
    healthcheck:
      test: [ "CMD-SHELL", "bash -c '</dev/tcp/localhost/1433'" ]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 20s
    networks:
      - course-network

  mssql-cmd:  # This container used for executing SQL scripts in SQL Server
    image: mcr.microsoft.com/mssql-tools:latest
    container_name: "mssql-cmd"
    depends_on:
      - mssql
    command: /opt/mssql/sql_scripts/run-initialization.sh
    stdin_open: true
    volumes:
      - ./mssql/sql_scripts:/opt/mssql/sql_scripts
    networks:
      - course-network

  zookeeper:
    image: debezium/zookeeper:2.7.3.Final
    restart: always
    container_name: "zookeeper"
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
    networks:
      - course-network

  kafka:
    build: ./kafka
    container_name: "kafka"
    depends_on:
      - zookeeper
    ports:
      - ${KAFKA_SERVICE_PORT}:${KAFKA_SERVICE_PORT}
      - 29092:29092
    environment:
      - KAFKA_BROKER_ID=${KAFKA_BROKER_ID}
      - KAFKA_ZOOKEEPER_CONNECT=${KAFKA_ZOOKEEPER_CONNECT}
      - KAFKA_ADVERTISED_LISTENERS=${KAFKA_ADVERTISED_LISTENERS}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      - KAFKA_INTER_BROKER_LISTENER_NAME=${KAFKA_INTER_BROKER_LISTENER_NAME}
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR}
    networks:
      - course-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: "kafka-ui"
    depends_on:
      - kafka
    ports:
      - 8090:8080
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    networks:
      - course-network

  storefront:
    container_name: "storefront"
    image: ghcr.io/online-language-learning-system/storefront-bff-image:1.0.0
    ports:
      - "8000:8000"
    environment:
      - KEYCLOAK_CLIENT_SECRET_STOREFRONT=${KEYCLOAK_CLIENT_SECRET_STOREFRONT}
      - KEYCLOAK_TOKEN_URI=${KEYCLOAK_TOKEN_URI}
      - KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
      - USER_SERVICE_URI=${USER_SERVICE_URI}
      - STOREFRONT_REACTJS_URI=${STOREFRONT_REACTJS_URI}
      - COURSE_SERVICE_URI=${COURSE_SERVICE_URI}
    networks:
      - course-network

  storefront-reactjs:
    container_name: "storefront-reactjs"
    image: storefront:latest
    ports:
      - "3000:80"
    networks:
      - course-network

  backoffice:
    container_name: "backoffice"
    image: ghcr.io/online-language-learning-system/backoffice-bff-image:1.0.0
    ports:
      - "8040:8040"
    environment:
      - KEYCLOAK_CLIENT_SECRET_BACKOFFICE=${KEYCLOAK_CLIENT_SECRET_BACKOFFICE}
      - KEYCLOAK_TOKEN_URI=${KEYCLOAK_TOKEN_URI}
      - KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
      - USER_SERVICE_URI=${USER_SERVICE_URI}
      - BACKOFFICE_REACTJS_URI=${BACKOFFICE_REACTJS_URI}
      - COURSE_SERVICE_URI=${COURSE_SERVICE_URI}
    networks:
      - course-network

  backoffice-reactjs:
    container_name: "backoffice-reactjs"
    image: backoffice:latest
    ports:
      - "3040:80"
    networks:
      - course-network

  user-service:
    container_name: "user-service"
    image: ghcr.io/online-language-learning-system/user-image:1.0.0
    ports:
      - "9000:9000"
    environment:
      - KEYCLOAK_SERVER_URI=${KEYCLOAK_SERVER_URI}
      - KEYCLOAK_CLIENT_SECRET_USER=${KEYCLOAK_CLIENT_SECRET_USER}
      - KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
    networks:
      - course-network

  cart-service:
    image: ghcr.io/online-language-learning-system/cart-image:1.0.0
    container_name: "cart-service"
    ports:
      - "9001:9001"
    environment:
      - KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
      - MSSQL_DATASOURCE_URL=${MSSQL_DATASOURCE_URL}
      - MSSQL_SA_USERNAME=${MSSQL_SA_USERNAME}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - KEYCLOAK_TOKEN_URL=${KEYCLOAK_TOKEN_URL}
    networks:
      - course-network

  media-service:
    image: ghcr.io/online-language-learning-system/media-image:1.0.0
    container_name: "media-service"
    ports:
      - "9003:9003"
    environment:
      - KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
    networks:
      - course-network

  course-service:
    image: ghcr.io/online-language-learning-system/course-image:1.0.1
    container_name: "course-service"
    ports:
      - "9002:9002"
    environment:
      - KEYCLOAK_ISSUER_URI=${KEYCLOAK_ISSUER_URI}
      - MSSQL_DATASOURCE_URL=${MSSQL_DATASOURCE_URL}
      - MSSQL_SA_USERNAME=${MSSQL_SA_USERNAME}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MEDIA_SERVICE=${MEDIA_SERVICE}
    networks:
      - course-network

networks:
  course-network:
    driver: bridge
    name: course-network